<?php
namespace Workerfy\Tests\MqttUnSub;

use Simps\MQTT\Client;

class Worker extends \Workerfy\AbstractProcess {

    public function run() {
        $config = [
            'host' => '127.0.0.1',
            'port' => 1884,
            'time_out' => 5,
            'user_name' => 'user001',
            'password' => 'hLXQ9ubnZGzkzf',
            'client_id' => 'd812edc1-18da-2085-0edf-a4a588c296d1'.rand(1,1000),
            'keep_alive' => 3,
        ];

        $client = new Client($config, ['open_mqtt_protocol' => true, 'package_max_length' => 2 * 1024 * 1024]);

        //$client = new \Simps\MQTT\ClientStream($config, ['open_mqtt_protocol' => true, 'package_max_length' => 2 * 1024 * 1024]);

        $will = [
            'topic' => 'simps-mqtt/user001/update',
            'qos' => 1,
            'retain' => 0,
            'message' => '' . time(),
        ];
        while (! $client->connect(false, $will)) {
            \Swoole\Coroutine::sleep(3);
            $client->connect(true, $will);
        }
        $topics = ['simps-mqtt/user001/get'];
        $res = $client->unsubscribe($topics);
        var_dump($res);
    }

    public function onShutDown()
    {
        parent::onShutDown(); // TODO: Change the autogenerated stub
        //var_dump("shutdown--");
    }

    public function onHandleException(\Throwable $throwable, array $context = [])
    {
        var_dump($throwable->getMessage()."-----trace:".$throwable->getTraceAsString());
    }

}