<?php
namespace Workerfy\Tests\Db;

use Workerfy\ProcessManager;
use PDO;

class Worker extends \Workerfy\AbstractProcess {

	public function run() {
	    if($this->getProcessWorkerId() == 0) {
            $db = \Workerfy\Tests\Db::getMasterMysql();
            $query = $db->query("select * from user limit 1");
            $res = $query->fetchAll(\PDO::FETCH_ASSOC);  //获取结果集中的所有数据
            var_dump($res);
            sleep(6);
            $this->reboot();
        }

	}

	public function onHandleException($throwable)
    {
        parent::onHandleException($throwable); // TODO: Change the autogenerated stub
        var_dump($throwable->getMessage());
    }
}