<?php
namespace Workerfy\Tests\MultiWorkerTraits;

use Workerfy\Tests\MultiWorkerTraits\Worker0;

class Worker extends \Workerfy\AbstractProcess {

    public function init() {}

    public function run() {
        // 模拟处理业务，按照user_id取模分发到不同的其他worker处理
        sleep(1);
        $worker_id = $this->getProcessWorkerId();
        switch ($worker_id) {
            case 0 :
                $worker = new Worker0($this);
                $worker->run();
                break;
            case 1 :

            case 2 :
        }
    }

    public function onShutDown()
    {
        parent::onShutDown(); // TODO: Change the autogenerated stub
        //var_dump("shutdown--");
    }

}