<?php
namespace Workerfy\Tests\MultiWorker;

use PDO;

class Worker1 extends \Workerfy\AbstractProcess {

    public function init() {}

    public function run() {
        // 模拟处理业务,比如消费user_id的尾号是1的队列
        sleep(1);
    }

    public function onShutDown()
    {
        parent::onShutDown(); // TODO: Change the autogenerated stub
        //var_dump("shutdown--");
    }

}