<?php
namespace Workerfy\Tests\Myexception;

class Worker extends \Workerfy\AbstractProcess {

    public function init() {
        defer(function() {
            //var_dump("coroutine_destruct");
        });
    }

    public function run() {
        var_dump("start redis test");
        // 模拟处理业务
        sleep(1);
        $redis = \Workerfy\Tests\Redis::getMasterRedis();
        $redis->set("name", "bingcool-".rand(1,1000));
        $value = $redis->get('name');
        var_dump($value);
    }

    public function onHandleException($throwable)
    {
        parent::onHandleException($throwable); // TODO: Change the autogenerated stub
        var_dump($throwable->getMessage());
    }
}