<?php
namespace Workerfy\Tests\DbSleep;

class Worker extends \Workerfy\AbstractProcess {

    public function run() {
        // 模拟处理业务
        //sleep(1);
        //var_dump("子进程 开始 reboot start");
        if($this->getProcessWorkerId() == 0) {
            while (1) {
                $db = \Workerfy\Tests\Make::makeMysql();
                $res = $db->query("select sleep(8)");
                var_dump($res);
                $this->reboot();
            }
        }

        if($this->getProcessWorkerId() == 1) {
            while (1) {
                $db = \Workerfy\Tests\Make::makeMysql();
                $res = $db->query("select sleep(3)");
                //var_dump($res);
                usleep(100000);
            }
        }
        //var_dump('worker'.$this->getProcessWorkerId());
    }

    public function onShutDown()
    {
        parent::onShutDown(); // TODO: Change the autogenerated stub
        //var_dump("shutdown--");
    }

    public function onHandleException(\Throwable $throwable, array $context = [])
    {
        var_dump($throwable->getMessage());
    }

}