<?php
namespace Workerfy\Tests\Dynamic;

class Worker extends \Workerfy\AbstractProcess {

    public function run() {
        // 模拟处理业务
        sleep(1);
        if($this->isStaticProcess()) {
           var_dump("静态进程启动:".$this->getProcessName().'@'.$this->getProcessWorkerId());
        }else {
            var_dump("动态进程启动:".$this->getProcessName().'@'.$this->getProcessWorkerId());
        }

    }

    public function onShutDown() {
        parent::onShutDown(); // TODO: Change the autogenerated stub

        if($this->isDynamicProcess()) {
            var_dump("动态进程销毁:".$this->getProcessName().'@'.$this->getProcessWorkerId());
        }
    }
}