<?php
namespace Workerfy\Tests\ReportStatus;

class Worker extends \Workerfy\AbstractProcess {

    public function run() {
        // 模拟处理业务
        //sleep(1);
        //var_dump("子进程 开始 reboot start");
        if($this->getProcessWorkerId() == 0) {
            while (1)
            {
                $db = \Workerfy\Tests\Make::makeMysql();
                $res = $db->query("SELECT * FROM tbl_users LIMIT 1");
                //var_dump($res);
                sleep(1);
            }

//            $this->reboot(); //可以观察到子进程pid在变化
//            $ids = $this->getCliEnvParam('ids');
//            $db = \Workerfy\Tests\Make::makeMysql();
//            $res = $db->query("SELECT * FROM tbl_users LIMIT 2");
//            var_dump($res);
//            sleep(1);
//            var_dump($ids);
//            $this->notifyMasterCreateDynamicProcess($this->getProcessName(),1);
//            $this->reboot();
        }

        if($this->getProcessWorkerId() == 1) {
            while (1) {
                $db = \Workerfy\Tests\Make::makeMysql();
                $res = $db->query("SELECT * FROM tbl_users LIMIT 1");
                //var_dump($res);
                sleep(1);
            }
        }

        if($this->getProcessWorkerId() == 2) {
            // 自身可以发起创建动态进程
            //$this->notifyMasterCreateDynamicProcess($this->getProcessName(),1);
        }
        //var_dump('worker'.$this->getProcessWorkerId());
    }

    public function onShutDown()
    {
        parent::onShutDown(); // TODO: Change the autogenerated stub
        //var_dump("shutdown--");
    }
}