<?php
namespace Workerfy\Tests\MYield;

class Worker extends \Workerfy\AbstractProcess {

    public function run() {
        // 模拟处理业务
        sleep(1);
        $start = 0;
        $limit = 5;
        $total = 20;
        $func = function($start) use($limit, $total) {
            while($start < $total) {
                $arr = [];
                var_dump('start:'.$start);
                for($i = $start; $i < ($start + $limit); $i++) {
                    $arr[] = $i;
                }
                $start = $i;
                yield $arr;
            }
            return [];

        };

        foreach($func($start) as $k=>$item) {
            var_dump($k);
            foreach($item as $value) {
                var_dump($value);
            }
        }

        var_dump('worker'.$this->getProcessWorkerId());
    }

    public function onShutDown()
    {
        parent::onShutDown(); // TODO: Change the autogenerated stub
        //var_dump("shutdown--");
    }

//    public function __destruct()
//    {
//        var_dump("destruct");
//    }
}