<?php
namespace Workerfy\Tests\Myexception;

class Worker extends \Workerfy\AbstractProcess {

    public function init() {
        defer(function() {
            //var_dump("coroutine_destruct");
        });
    }

    public function run() {
        // 抛出异常
        throw new \Exception("test workerfy exception");
    }

    public function onHandleException($throwable)
    {
        parent::onHandleException($throwable); // TODO: Change the autogenerated stub
        var_dump("Exception:".$throwable->getMessage());
    }
}