<?php
namespace Workerfy\Tests\Exits;

class Worker extends \Workerfy\AbstractProcess {

    public function run() {

        // 模拟处理业务
        sleep(10);
        var_dump("子进程开始自动退出");
        $this->exit(); //可以观察到子进程最终销毁掉
    }

    public function onShutDown()
    {
        parent::onShutDown(); // TODO: Change the autogenerated stub
        var_dump("子进程退出");
    }
}